version: '3.3'

services:
  mongodb:
    image: mongo:3.4-xenial
    restart: always
    volumes:
      - v-mongodb:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: xxxxx
    #  MONGO_INITDB_ROOT_PASSWORD: xxxxx
  
  backend:
    image: asc-backend-image
    restart: always
    build: ./backend/
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 3000:3000
    depends_on: 
      - mongodb
    environment:
      DEBUG: "app:*"
      #DEBUG: app:checkAIP
      MongoDbHost: mongodb
      MongoDbSid: ascdb
  
  frontend: 
    image: asc-frontend-image
    restart: always
    build: ./frontend/
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      BackEndHost: backend
    ports:
      - 8082:8082
    depends_on:
      - backend

volumes:
  v-mongodb: